[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.prod"

[deploy]
startCommand = "bash scripts/railway_deploy.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5